[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DeftPunk"
version = "0.1.0"
description = "Defect detection and tracking toolkit for nematic textures"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}  # or your actual license
authors = [{name = "Your Name"}]



# Runtime deps for *your library* (not the napari plugin)
dependencies = [
  "numpy",
  "pandas",
  "matplotlib",
  "tifffile",
  "trackpy",
  "scipy",
  "qtpy"
]

[project.optional-dependencies]
full = [
  "scikit-image",
]

[tool.setuptools.packages.find]
include = ["DeftPunk*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"DeftPunk" = ["GUI_images/*.jpg", "GUI_images/*.png", "/home/quentin/DeftPunk/DeftPunk/processing/ref_epsilon/*.npy"]
